name: Build & Deploy Diagram

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'HTMLファイル名（例：test）'
        required: true
      infile:
        description: '入力テキストパス（例：input/test.txt）'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install openai

      - name: Generate HTML
        run: |
          python scripts/make_diagram.py "${{ inputs.slug }}" "${{ inputs.infile }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit to gh-pages
        run: |
          git switch -C gh-pages
          git add docs/${{ inputs.slug }}.html
          git commit -m "Add diagram: ${{ inputs.slug }}"
          git push origin gh-pages
